---
- name: List IPs using AWX
  hosts: all
  gather_facts: false
  tasks:
    - name: Add hosts dynamically
      add_host:
        name: "{{ item }}"
        groups: dynamic_hosts
      loop:
        - 192.168.1.10
        - 192.168.1.20
        - 192.168.1.30

    - name: Display IP addresses
      debug:
        var: hostvars[item].ansible_default_ipv4.address
      loop: "{{ groups['dynamic_hosts'] }}"
