---
- name: Read Secret from HashiCorp Vault
  hosts: all  # Adjust the target hosts as needed
  gather_facts: false
  tasks:
    - name: Read secret from Vault
      community.hashi_vault.read:
        vault_identity: "vault"  # Replace with your AWX Vault credential name
        path: "/secret/data/my_secret"  # Replace with the actual path in Vault
      register: vault_result

    - name: Debug Vault result
      debug:
        var: vault_result

