---
- name: Example Playbook with Vault
  hosts: all
  gather_facts: true
  tasks:
    - name: Read a secret from Vault
        global_secrets: "{{ lookup('hashi_vault', lookup_options) }}"
        vault_identity: "vault"  # Replace with your AWX Vault credential name
        path: "/v1/secret/data/secret/example"
      register: vault_result

    - name: Debug Vault result
      debug:
        var: vault_result

